//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skene.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public string LastUsedSetup {
            get {
                return ((string)(this["LastUsedSetup"]));
            }
            set {
                this["LastUsedSetup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TargetsFile {
            get {
                return ((string)(this["TargetsFile"]));
            }
            set {
                this["TargetsFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\Utterances")]
        public string UtteranceLibrariesDirectory {
            get {
                return ((string)(this["UtteranceLibrariesDirectory"]));
            }
            set {
                this["UtteranceLibrariesDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\Utterances\\ValidationSets")]
        public string UtteranceValidatorsDirectory {
            get {
                return ((string)(this["UtteranceValidatorsDirectory"]));
            }
            set {
                this["UtteranceValidatorsDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UtteranceValidationSet {
            get {
                return ((string)(this["UtteranceValidationSet"]));
            }
            set {
                this["UtteranceValidationSet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseCompositeLibrary {
            get {
                return ((bool)(this["UseCompositeLibrary"]));
            }
            set {
                this["UseCompositeLibrary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SelectedLibrary {
            get {
                return ((string)(this["SelectedLibrary"]));
            }
            set {
                this["SelectedLibrary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double DefaultGazeSpeed {
            get {
                return ((double)(this["DefaultGazeSpeed"]));
            }
            set {
                this["DefaultGazeSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int QuestionsFinishEventDelaySeconds {
            get {
                return ((int)(this["QuestionsFinishEventDelaySeconds"]));
            }
            set {
                this["QuestionsFinishEventDelaySeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseUtteranceRelativeSpeed {
            get {
                return ((bool)(this["UseUtteranceRelativeSpeed"]));
            }
            set {
                this["UseUtteranceRelativeSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75")]
        public int UtteranceRelativeSpeed {
            get {
                return ((int)(this["UtteranceRelativeSpeed"]));
            }
            set {
                this["UtteranceRelativeSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StripSlashes {
            get {
                return ((bool)(this["StripSlashes"]));
            }
            set {
                this["StripSlashes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>coiso</string>\r\n  <string>asdasd</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection TestTags {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TestTags"]));
            }
            set {
                this["TestTags"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BackchannelingCategory {
            get {
                return ((string)(this["BackchannelingCategory"]));
            }
            set {
                this["BackchannelingCategory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public int UtteranceTimeoutMs {
            get {
                return ((int)(this["UtteranceTimeoutMs"]));
            }
            set {
                this["UtteranceTimeoutMs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public float UtterancesSafeDurationSeconds {
            get {
                return ((float)(this["UtterancesSafeDurationSeconds"]));
            }
            set {
                this["UtterancesSafeDurationSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseUtterancesSafeDuration {
            get {
                return ((bool)(this["UseUtterancesSafeDuration"]));
            }
            set {
                this["UseUtterancesSafeDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double ZTrackingCompensation {
            get {
                return ((double)(this["ZTrackingCompensation"]));
            }
            set {
                this["ZTrackingCompensation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-10")]
        public double YTrackingCompensation {
            get {
                return ((double)(this["YTrackingCompensation"]));
            }
            set {
                this["YTrackingCompensation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PerformEstablishingGaze {
            get {
                return ((bool)(this["PerformEstablishingGaze"]));
            }
            set {
                this["PerformEstablishingGaze"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PerformGazeBreaking {
            get {
                return ((bool)(this["PerformGazeBreaking"]));
            }
            set {
                this["PerformGazeBreaking"] = value;
            }
        }
    }
}
