/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace GBML {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class bml : BehaviorBlock {
        
        private BehaviorBlock[] requiredField;
        
        private Constraint[] constraintField;
        
        private string idField;
        
        private string characterField;
        
        private string compositionField;
        
        public bml() {
            this.characterField = "\"\"";
            this.compositionField = "MERGE";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("required")]
        public BehaviorBlock[] required {
            get {
                return this.requiredField;
            }
            set {
                this.requiredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("constraint")]
        public Constraint[] constraint {
            get {
                return this.constraintField;
            }
            set {
                this.constraintField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("\"\"")]
        public string character {
            get {
                return this.characterField;
            }
            set {
                this.characterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("MERGE")]
        public string composition {
            get {
                return this.compositionField;
            }
            set {
                this.compositionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BehaviorBlock {
        
        private Face[] faceField;
        
        private FaceLexeme[] faceLexemeField;
        
        private FaceFacs[] faceFacsField;
        
        private FaceShift[] faceShiftField;
        
        private Gaze[] gazeField;
        
        private GazeShift[] gazeShiftField;
        
        private Gesture[] gestureField;
        
        private Pointing[] pointingField;
        
        private Head[] headField;
        
        private HeadDirectionShift[] headDirectionShiftField;
        
        private Locomotion[] locomotionField;
        
        private Posture[] postureField;
        
        private PostureShift[] postureShiftField;
        
        private Speech[] speechField;
        
        private Animation[] animationField;
        
        private Sound[] soundField;
        
        private Wait[] waitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("face")]
        public Face[] face {
            get {
                return this.faceField;
            }
            set {
                this.faceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("faceLexeme")]
        public FaceLexeme[] faceLexeme {
            get {
                return this.faceLexemeField;
            }
            set {
                this.faceLexemeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("faceFacs")]
        public FaceFacs[] faceFacs {
            get {
                return this.faceFacsField;
            }
            set {
                this.faceFacsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("faceShift")]
        public FaceShift[] faceShift {
            get {
                return this.faceShiftField;
            }
            set {
                this.faceShiftField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("gaze")]
        public Gaze[] gaze {
            get {
                return this.gazeField;
            }
            set {
                this.gazeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("gazeShift")]
        public GazeShift[] gazeShift {
            get {
                return this.gazeShiftField;
            }
            set {
                this.gazeShiftField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("gesture")]
        public Gesture[] gesture {
            get {
                return this.gestureField;
            }
            set {
                this.gestureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pointing")]
        public Pointing[] pointing {
            get {
                return this.pointingField;
            }
            set {
                this.pointingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("head")]
        public Head[] head {
            get {
                return this.headField;
            }
            set {
                this.headField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("headDirectionShift")]
        public HeadDirectionShift[] headDirectionShift {
            get {
                return this.headDirectionShiftField;
            }
            set {
                this.headDirectionShiftField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("locomotion")]
        public Locomotion[] locomotion {
            get {
                return this.locomotionField;
            }
            set {
                this.locomotionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("posture")]
        public Posture[] posture {
            get {
                return this.postureField;
            }
            set {
                this.postureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("postureShift")]
        public PostureShift[] postureShift {
            get {
                return this.postureShiftField;
            }
            set {
                this.postureShiftField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("speech")]
        public Speech[] speech {
            get {
                return this.speechField;
            }
            set {
                this.speechField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("animation")]
        public Animation[] animation {
            get {
                return this.animationField;
            }
            set {
                this.animationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sound")]
        public Sound[] sound {
            get {
                return this.soundField;
            }
            set {
                this.soundField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("wait")]
        public Wait[] wait {
            get {
                return this.waitField;
            }
            set {
                this.waitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FaceShift))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Face : FaceBase {
        
        private FaceFacs[] facsField;
        
        private FaceLexeme[] lexemeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("facs")]
        public FaceFacs[] facs {
            get {
                return this.facsField;
            }
            set {
                this.facsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("lexeme")]
        public FaceLexeme[] lexeme {
            get {
                return this.lexemeField;
            }
            set {
                this.lexemeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FaceFacs : FaceBase {
        
        private int auField;
        
        private bool auFieldSpecified;
        
        private FacsSide sideField;
        
        private bool sideFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int au {
            get {
                return this.auField;
            }
            set {
                this.auField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool auSpecified {
            get {
                return this.auFieldSpecified;
            }
            set {
                this.auFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public FacsSide side {
            get {
                return this.sideField;
            }
            set {
                this.sideField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sideSpecified {
            get {
                return this.sideFieldSpecified;
            }
            set {
                this.sideFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    public enum FacsSide {
        
        /// <remarks/>
        LEFT,
        
        /// <remarks/>
        RIGHT,
        
        /// <remarks/>
        BOTH,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FaceLexeme))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FaceFacs))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Face))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FaceShift))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FaceBase : ActionBlock {
        
        private float amountField;
        
        private string attackPeakField;
        
        private string relaxField;
        
        private string overshootField;
        
        public FaceBase() {
            this.amountField = ((float)(1F));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "1")]
        public float amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string attackPeak {
            get {
                return this.attackPeakField;
            }
            set {
                this.attackPeakField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string relax {
            get {
                return this.relaxField;
            }
            set {
                this.relaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string overshoot {
            get {
                return this.overshootField;
            }
            set {
                this.overshootField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Wait))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Animation))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Sound))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Speech))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PostureBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PostureShift))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Posture))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Locomotion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HeadDirectionShift))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Head))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Pointing))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Gesture))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GazeBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GazeShift))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Gaze))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FaceBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FaceLexeme))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FaceFacs))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Face))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FaceShift))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActionBlock {
        
        private string idField;
        
        private string startField;
        
        private string endField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string end {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Before {
        
        private Sync[] syncField;
        
        private string refField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sync")]
        public Sync[] sync {
            get {
                return this.syncField;
            }
            set {
                this.syncField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @ref {
            get {
                return this.refField;
            }
            set {
                this.refField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Sync {
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class After {
        
        private Sync[] syncField;
        
        private string refField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sync")]
        public Sync[] sync {
            get {
                return this.syncField;
            }
            set {
                this.syncField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @ref {
            get {
                return this.refField;
            }
            set {
                this.refField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Synchronize {
        
        private Sync[] syncField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sync")]
        public Sync[] sync {
            get {
                return this.syncField;
            }
            set {
                this.syncField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Constraint {
        
        private Synchronize synchronizeField;
        
        private After afterField;
        
        private Before beforeField;
        
        private string idField;
        
        /// <remarks/>
        public Synchronize synchronize {
            get {
                return this.synchronizeField;
            }
            set {
                this.synchronizeField = value;
            }
        }
        
        /// <remarks/>
        public After after {
            get {
                return this.afterField;
            }
            set {
                this.afterField = value;
            }
        }
        
        /// <remarks/>
        public Before before {
            get {
                return this.beforeField;
            }
            set {
                this.beforeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TextBlock {
        
        private Sync[] syncField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sync")]
        public Sync[] sync {
            get {
                return this.syncField;
            }
            set {
                this.syncField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Pose {
        
        private BodyPart partField;
        
        private bool partFieldSpecified;
        
        private LexemePose lexemeField;
        
        private bool lexemeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public BodyPart part {
            get {
                return this.partField;
            }
            set {
                this.partField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool partSpecified {
            get {
                return this.partFieldSpecified;
            }
            set {
                this.partFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public LexemePose lexeme {
            get {
                return this.lexemeField;
            }
            set {
                this.lexemeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lexemeSpecified {
            get {
                return this.lexemeFieldSpecified;
            }
            set {
                this.lexemeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    public enum BodyPart {
        
        /// <remarks/>
        HAND,
        
        /// <remarks/>
        LEFT_HAND,
        
        /// <remarks/>
        RIGHT_HAND,
        
        /// <remarks/>
        BOTH_HANDS,
        
        /// <remarks/>
        HEAD,
        
        /// <remarks/>
        FOOT,
        
        /// <remarks/>
        RIGHT_FOOT,
        
        /// <remarks/>
        LEFT_FOOT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    public enum LexemePose {
        
        /// <remarks/>
        ARMS_AKIMBO,
        
        /// <remarks/>
        ARMS_CROSSED,
        
        /// <remarks/>
        ARMS_NEUTRAL,
        
        /// <remarks/>
        ARMS_OPEN,
        
        /// <remarks/>
        LEGS_CROSSED,
        
        /// <remarks/>
        LEGS_NEUTRAL,
        
        /// <remarks/>
        LEGS_OPEN,
        
        /// <remarks/>
        LEANING_FORWARD,
        
        /// <remarks/>
        LEANING_BACKWARD,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Stance {
        
        private StanceType typeField;
        
        private bool typeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public StanceType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    public enum StanceType {
        
        /// <remarks/>
        SITTING,
        
        /// <remarks/>
        CROUCHING,
        
        /// <remarks/>
        STANDING,
        
        /// <remarks/>
        LYING,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Wait : ActionBlock {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Animation : ActionBlock {
        
        private string nameField;
        
        private AnimationInfluence influenceField;
        
        private bool influenceFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AnimationInfluence Influence {
            get {
                return this.influenceField;
            }
            set {
                this.influenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InfluenceSpecified {
            get {
                return this.influenceFieldSpecified;
            }
            set {
                this.influenceFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    public enum AnimationInfluence {
        
        /// <remarks/>
        RIGHTARM,
        
        /// <remarks/>
        LEFTARM,
        
        /// <remarks/>
        BOTHARMS,
        
        /// <remarks/>
        RIGHTLEG,
        
        /// <remarks/>
        LEFTLEG,
        
        /// <remarks/>
        BOTHLEGS,
        
        /// <remarks/>
        FULLBODY,
        
        /// <remarks/>
        HEAD,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Sound : ActionBlock {
        
        private string soundNameField;
        
        private SoundPlayMode modeField;
        
        private bool modeFieldSpecified;
        
        private float volumeField;
        
        private bool volumeFieldSpecified;
        
        private float pitchField;
        
        private bool pitchFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SoundName {
            get {
                return this.soundNameField;
            }
            set {
                this.soundNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SoundPlayMode Mode {
            get {
                return this.modeField;
            }
            set {
                this.modeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ModeSpecified {
            get {
                return this.modeFieldSpecified;
            }
            set {
                this.modeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float Volume {
            get {
                return this.volumeField;
            }
            set {
                this.volumeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VolumeSpecified {
            get {
                return this.volumeFieldSpecified;
            }
            set {
                this.volumeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float Pitch {
            get {
                return this.pitchField;
            }
            set {
                this.pitchField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PitchSpecified {
            get {
                return this.pitchFieldSpecified;
            }
            set {
                this.pitchFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    public enum SoundPlayMode {
        
        /// <remarks/>
        REGULAR,
        
        /// <remarks/>
        LOOP,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Speech : ActionBlock {
        
        private TextBlock textField;
        
        /// <remarks/>
        public TextBlock text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PostureShift))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Posture))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostureBase : ActionBlock {
        
        private Stance[] stanceField;
        
        private Pose[] poseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("stance")]
        public Stance[] stance {
            get {
                return this.stanceField;
            }
            set {
                this.stanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pose")]
        public Pose[] pose {
            get {
                return this.poseField;
            }
            set {
                this.poseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostureShift : PostureBase {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Posture : PostureBase {
        
        private string readyField;
        
        private string relaxField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ready {
            get {
                return this.readyField;
            }
            set {
                this.readyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string relax {
            get {
                return this.relaxField;
            }
            set {
                this.relaxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Locomotion : ActionBlock {
        
        private string targetField;
        
        private WalkType mannerField;
        
        public Locomotion() {
            this.mannerField = WalkType.WALK;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string target {
            get {
                return this.targetField;
            }
            set {
                this.targetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(WalkType.WALK)]
        public WalkType manner {
            get {
                return this.mannerField;
            }
            set {
                this.mannerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    public enum WalkType {
        
        /// <remarks/>
        WALK,
        
        /// <remarks/>
        RUN,
        
        /// <remarks/>
        STRAFE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HeadDirectionShift : ActionBlock {
        
        private string targetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string target {
            get {
                return this.targetField;
            }
            set {
                this.targetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Head : ActionBlock {
        
        private string relaxField;
        
        private string readyField;
        
        private string strokeStartField;
        
        private string strokeField;
        
        private string strokeEndField;
        
        private LexemeHead lexemeField;
        
        private bool lexemeFieldSpecified;
        
        private int repetitionField;
        
        private float amountField;
        
        public Head() {
            this.repetitionField = 1;
            this.amountField = ((float)(1F));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string relax {
            get {
                return this.relaxField;
            }
            set {
                this.relaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ready {
            get {
                return this.readyField;
            }
            set {
                this.readyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string strokeStart {
            get {
                return this.strokeStartField;
            }
            set {
                this.strokeStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string stroke {
            get {
                return this.strokeField;
            }
            set {
                this.strokeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string strokeEnd {
            get {
                return this.strokeEndField;
            }
            set {
                this.strokeEndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public LexemeHead lexeme {
            get {
                return this.lexemeField;
            }
            set {
                this.lexemeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lexemeSpecified {
            get {
                return this.lexemeFieldSpecified;
            }
            set {
                this.lexemeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(1)]
        public int repetition {
            get {
                return this.repetitionField;
            }
            set {
                this.repetitionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "1")]
        public float amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    public enum LexemeHead {
        
        /// <remarks/>
        NOD,
        
        /// <remarks/>
        SHAKE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Pointing : ActionBlock {
        
        private BodyPart modeField;
        
        private bool modeFieldSpecified;
        
        private string targetField;
        
        private string relaxField;
        
        private string readyField;
        
        private string strokeStartField;
        
        private string strokeField;
        
        private string strokeEndField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public BodyPart mode {
            get {
                return this.modeField;
            }
            set {
                this.modeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool modeSpecified {
            get {
                return this.modeFieldSpecified;
            }
            set {
                this.modeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string target {
            get {
                return this.targetField;
            }
            set {
                this.targetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string relax {
            get {
                return this.relaxField;
            }
            set {
                this.relaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ready {
            get {
                return this.readyField;
            }
            set {
                this.readyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string strokeStart {
            get {
                return this.strokeStartField;
            }
            set {
                this.strokeStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string stroke {
            get {
                return this.strokeField;
            }
            set {
                this.strokeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string strokeEnd {
            get {
                return this.strokeEndField;
            }
            set {
                this.strokeEndField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Gesture : ActionBlock {
        
        private BodyPart modeField;
        
        private bool modeFieldSpecified;
        
        private LexemeGesture lexemeField;
        
        private bool lexemeFieldSpecified;
        
        private string readyField;
        
        private string strokeStartField;
        
        private string strokeField;
        
        private string strokeEndField;
        
        private string relaxField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public BodyPart mode {
            get {
                return this.modeField;
            }
            set {
                this.modeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool modeSpecified {
            get {
                return this.modeFieldSpecified;
            }
            set {
                this.modeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public LexemeGesture lexeme {
            get {
                return this.lexemeField;
            }
            set {
                this.lexemeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lexemeSpecified {
            get {
                return this.lexemeFieldSpecified;
            }
            set {
                this.lexemeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ready {
            get {
                return this.readyField;
            }
            set {
                this.readyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string strokeStart {
            get {
                return this.strokeStartField;
            }
            set {
                this.strokeStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string stroke {
            get {
                return this.strokeField;
            }
            set {
                this.strokeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string strokeEnd {
            get {
                return this.strokeEndField;
            }
            set {
                this.strokeEndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string relax {
            get {
                return this.relaxField;
            }
            set {
                this.relaxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    public enum LexemeGesture {
        
        /// <remarks/>
        BEAT,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GazeShift))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Gaze))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GazeBase : ActionBlock {

        private float speedField;

        private bool speedFieldSpecified;

        private string targetField;
        
        private string influenceField;
        
        private float offsetangleField;
        
        private bool offsetangleFieldSpecified;
        
        private Direction offsetdirectionField;
        
        private bool offsetdirectionFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float speed
        {
            get
            {
                return this.speedField;
            }
            set
            {
                this.speedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool speedSpecified
        {
            get
            {
                return this.speedFieldSpecified;
            }
            set
            {
                this.speedFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string target {
            get {
                return this.targetField;
            }
            set {
                this.targetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string influence {
            get {
                return this.influenceField;
            }
            set {
                this.influenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float offsetangle {
            get {
                return this.offsetangleField;
            }
            set {
                this.offsetangleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool offsetangleSpecified {
            get {
                return this.offsetangleFieldSpecified;
            }
            set {
                this.offsetangleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Direction offsetdirection {
            get {
                return this.offsetdirectionField;
            }
            set {
                this.offsetdirectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool offsetdirectionSpecified {
            get {
                return this.offsetdirectionFieldSpecified;
            }
            set {
                this.offsetdirectionFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    public enum Direction {
        
        /// <remarks/>
        RIGHT,
        
        /// <remarks/>
        LEFT,
        
        /// <remarks/>
        UP,
        
        /// <remarks/>
        DOWN,
        
        /// <remarks/>
        UPRIGHT,
        
        /// <remarks/>
        UPLEFT,
        
        /// <remarks/>
        DOWNLEFT,
        
        /// <remarks/>
        DOWNRIGHT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GazeShift : GazeBase {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Gaze : GazeBase {
        
        private string readyField;
        
        private string relaxField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ready {
            get {
                return this.readyField;
            }
            set {
                this.readyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string relax {
            get {
                return this.relaxField;
            }
            set {
                this.relaxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FaceLexeme : FaceBase {
        
        private string lexemeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string lexeme {
            get {
                return this.lexemeField;
            }
            set {
                this.lexemeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FaceShift : Face {
    }
}
