package uk.co.emote;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "competencyevidienceitemlink")
public class CompetencyEvidienceItemLink {

	@Id
	// @Id indicates that this it a unique primary key
	@GeneratedValue
	// @GeneratedValue indicates that value is automatically generated by the
	// server
	private int id;

	@Column
	private String competencyName;

	@Column
	private String evidenceItemType;

	@Column
	private int weight;

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCompetencyName() {
		return competencyName;
	}

	public void setCompetencyName(String competencyName) {
		this.competencyName = competencyName;
	}

	public String getEvidenceItemType() {
		return evidenceItemType;
	}

	public void setEvidenceItemType(String evidenceItemType) {
		this.evidenceItemType = evidenceItemType;
	}

	public int getWeight() {
		return weight;
	}

	public void setWeight(int weight) {
		this.weight = weight;
	}

}
