package uk.co.emote;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

@Entity
@Table(name = "dbcompetency")
public class DbCompetency {

	 @Id // @Id indicates that this it a unique primary key
	    @GeneratedValue // @GeneratedValue indicates that value is automatically generated by the server
	    private int id;
	 
	 @ManyToOne
	    private Learner learner;
	 
	 @ManyToOne
	    private Session session;
	
	 @Column(length = 32, unique = false)
	    // the optional @Column allows us makes sure that the name is limited to a suitable size and is unique
	    private String name;
	 

	public int getId() {
		return id;
	}


	public void setId(int id) {
		this.id = id;
	}


	public Learner getLearner() {
		return learner;
	}


	public void setLearner(Learner learner) {
		this.learner = learner;
	}


	public Session getSession() {
		return session;
	}


	public void setSession(Session session) {
		this.session = session;
	}


	public String getName() {
		return name;
	}


	public void setName(String name) {
		this.name = name;
	}

	 
	 
}
