package uk.co.emote;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

@Entity
@Table(name = "enercitiesGameInfoDB")
public class EnercitiesGameInfoDB {

	 @Id // @Id indicates that this it a unique primary key
	    @GeneratedValue // @GeneratedValue indicates that value is automatically generated by the server
	    private int id;
	 
	 @ManyToOne
	    private Learner learner;
	 	 
	 @ManyToOne
	    private Session session;
	 
	 @Column
	 private Integer stepId; 
	 
	 @Column
		private Integer activityId;
		
	 @Column
	 private Integer scenarioId;
		
	 @Column
	 private Integer emoteScenarioId;
	 
	 @Column
	private String CurrentRole;
	
	 @Column
	 private Double EconomyScore;
	
	 @Column
	 private Double EnvironmentScore;
	 
	 @Column
	private Double GlobalScore;
	 
	 @Column
	private Integer Level;
	 
	 @Column
	private Double Money;
	 
	 @Column
	private Double MoneyEarning;
	 
	 @Column
	private Double Oil;
	 
	 @Column
	private Integer Population;
	 
	 @Column
	private Double PowerConsumption;
	 
	 @Column
    private Double PowerProduction;
	 
	 @Column
    private Integer TargetPopulation;
	 
	 @Column
    private Double WellbeingScore;
    
	public String getCurrentRole() {
		return CurrentRole;
	}
	public void setCurrentRole(String currentRole) {
		CurrentRole = currentRole;
	}
	public Double getEconomyScore() {
		return EconomyScore;
	}
	public void setEconomyScore(Double economyScore) {
		EconomyScore = economyScore;
	}
	public Double getEnvironmentScore() {
		return EnvironmentScore;
	}
	public void setEnvironmentScore(Double environmentScore) {
		EnvironmentScore = environmentScore;
	}
	public Double getGlobalScore() {
		return GlobalScore;
	}
	public void setGlobalScore(Double globalScore) {
		GlobalScore = globalScore;
	}
	public Integer getLevel() {
		return Level;
	}
	public void setLevel(Integer level) {
		Level = level;
	}
	public Double getMoney() {
		return Money;
	}
	public void setMoney(Double money) {
		Money = money;
	}
	public Double getMoneyEarning() {
		return MoneyEarning;
	}
	public void setMoneyEarning(Double moneyEarning) {
		MoneyEarning = moneyEarning;
	}
	public Double getOil() {
		return Oil;
	}
	public void setOil(Double oil) {
		Oil = oil;
	}
	public Integer getPopulation() {
		return Population;
	}
	public void setPopulation(Integer population) {
		Population = population;
	}
	public Double getPowerConsumption() {
		return PowerConsumption;
	}
	public void setPowerConsumption(Double powerConsumption) {
		PowerConsumption = powerConsumption;
	}
	public Double getPowerProduction() {
		return PowerProduction;
	}
	public void setPowerProduction(Double powerProduction) {
		PowerProduction = powerProduction;
	}
	public Integer getTargetPopulation() {
		return TargetPopulation;
	}
	public void setTargetPopulation(Integer targetPopulation) {
		TargetPopulation = targetPopulation;
	}
	public Double getWellbeingScore() {
		return WellbeingScore;
	}
	public void setWellbeingScore(Double wellbeingScore) {
		WellbeingScore = wellbeingScore;
	}
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}

	public Session getSession() {
		return session;
	}
	public void setSession(Session session) {
		this.session = session;
	}
	public Integer getStepId() {
		return stepId;
	}
	public void setStepId(Integer stepId) {
		this.stepId = stepId;
	}
	public Integer getActivityId() {
		return activityId;
	}
	public void setActivityId(Integer activityId) {
		this.activityId = activityId;
	}
	public Integer getScenarioId() {
		return scenarioId;
	}
	public void setScenarioId(Integer scenarioId) {
		this.scenarioId = scenarioId;
	}
	public Integer getEmoteScenarioId() {
		return emoteScenarioId;
	}
	public void setEmoteScenarioId(Integer emoteScenarioId) {
		this.emoteScenarioId = emoteScenarioId;
	}
	public Learner getLearner() {
		return learner;
	}
	public void setLearner(Learner learner) {
		this.learner = learner;
	}
	
    
}
