package uk.co.emote;

import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * @author AXJ100
 *
 */
@Entity
@Table(name = "utterance")
public class Utterance {

	 @Id // @Id indicates that this it a unique primary key
	    @GeneratedValue // @GeneratedValue indicates that value is automatically generated by the server
	    private int id;
	 
	 @Column(length = 1024, unique = false)	  
		private String utteranceId;
	
	 @ManyToOne
	    private Learner learner;
	
	 @Column(length = 1024, unique = false)
		private String utterance;
	 
	 @Column(length = 32, unique = false)
		private String category;
	 
	 @Column(length = 32, unique = false)
		private String subcategory;
		
		 @Column
		    // the optional @Column allows us makes sure that the name is limited to a suitable size and is unique
		    private Date start;
		 
		 @Column
		    // the optional @Column allows us makes sure that the name is limited to a suitable size and is unique
		    private Date end;
		 
		 @Column
		    // the optional @Column allows us makes sure that the name is limited to a suitable size and is unique
		    private Date canceledTime;

		 @Column
		  private Boolean canceled;
		 
		 @Column
		  private Boolean question;
		 
		 @Column
			private String library;
		 
		 @Column
			private String repetitions;
		 
		 @Column
		 private String libraryId;
		 
		 @Column
		 private String sessionNumber;
		 
		public int getId() {
			return id;
		}

		public void setId(int id) {
			this.id = id;
		}



		public String getUtteranceId() {
			return utteranceId;
		}

		public void setUtteranceId(String utteranceId) {
			this.utteranceId = utteranceId;
		}

		public Learner getLearner() {
			return learner;
		}

		public void setLearner(Learner learner) {
			this.learner = learner;
		}

		public String getUtterance() {
			return utterance;
		}

		public void setUtterance(String utterance) {
			this.utterance = utterance;
		}

		public String getCategory() {
			return category;
		}

		public void setCategory(String category) {
			this.category = category;
		}

		public String getSubcategory() {
			return subcategory;
		}

		public void setSubcategory(String subcategory) {
			this.subcategory = subcategory;
		}

		public Date getStart() {
			return start;
		}

		public void setStart(Date start) {
			this.start = start;
		}

		public Date getEnd() {
			return end;
		}

		public void setEnd(Date end) {
			this.end = end;
		}

		public Date getCanceledTime() {
			return canceledTime;
		}

		public void setCanceledTime(Date canceledTime) {
			this.canceledTime = canceledTime;
		}

		public Boolean getCanceled() {
			return canceled;
		}

		public void setCanceled(Boolean canceled) {
			this.canceled = canceled;
		}

		public Boolean getQuestion() {
			return question;
		}

		public void setQuestion(Boolean question) {
			this.question = question;
		}

		public String getLibrary() {
			return library;
		}

		public void setLibrary(String library) {
			this.library = library;
		}

		public String getRepetitions() {
			return repetitions;
		}

		public void setRepetitions(String repetitions) {
			this.repetitions = repetitions;
		}

		public String getLibraryId() {
			return libraryId;
		}

		public void setLibraryId(String libraryId) {
			this.libraryId = libraryId;
		}

		public String getSessionNumber() {
			return sessionNumber;
		}

		public void setSessionNumber(String sessionNumber) {
			this.sessionNumber = sessionNumber;
		}
		
		


}
